services:
  auth:
    image: ghcr.io/navikt/mock-oauth2-server:2.0.0
    ports:
      - 9999:8080
  db:
    image: postgres:15.2-bullseye
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./db/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 9090:8080
    environment:
      ADMINER_DESIGN: dracula
  shopping:
    image: jeffrygonzalez/shopping-api-nov-2023:v1.1
    ports:
      - 1340:80
    environment:
      ConnectionStrings__database: Server=db;Port=5432;Database=shopping;User Id=user;Password=password;
volumes:
  db_data: